### ISSUE TITLE
SpEyeGaze - ScreenCapture::CaptureRegion can throw Win32 exception and bring down the application

### ISSUE THREAD

**Issue by joncamp** [TeamGleason/SpeakFaster#5]
Currently throws a new Win32Exception when BitBlt fails

**Comment by TeamGleasonDev** [comment]
I think this was a ram leak issue that I fixed.

Have moved back to the .NET capture API rather than the PInvoke because I was having troubles getting the BMP format of the PInvoke capture (BGRX pixel format I think?) to be compatible with libjpeg-turbo, and the perf was better with (slow).netcapture-(fast)libjpeg-turbo than (fast)pinvokecapture-(slow).netjpegencoder.
